version: 0.11.{build}
image:
- Visual Studio 2019

build:
  verbosity: minimal

branches:
  except:
  - gh-pages

init:
- git config --global core.autocrlf input

install:
- git submodule update --init --recursive --remote
- ps: ./install.ps1

build_script:
- ps: dotnet build -c Release
- ps: dotnet paket update -g refdoc
- ps: cp build/docs/reference.html src/Website/docs/reference/template.cshtml
- ps: dotnet fsformatting metadataformat
        --generate --outdir "$(mkdir -force build/docs/reference)"
        --layoutRoots src/Website/docs/reference packages/fsformatting/FSharp.Formatting/templates/reference
        --sourceRepo https://github.com/fsbolero/bolero
        --sourceFolder .
        --parameters
          project-name "Bolero"
          project-author "IntelliFactory and contributors"
          project-summary "A set of tools and libraries to run F# applications in WebAssembly using Blazor"
          project-github "https://github.com/fsbolero/bolero"
          project-nuget "https://nuget.org/packages/Bolero"
          root "/docs"
        --libDirs
          packages/refdoc/Elmish/lib/netstandard2.0
          packages/refdoc/Microsoft.AspNetCore.Components/lib/netstandard2.0
          packages/refdoc/Microsoft.AspNetCore.Components.Web/lib/netstandard2.0
          packages/refdoc/Microsoft.AspNetCore.Components.WebAssembly/lib/netstandard2.1
          packages/refdoc/Microsoft.AspNetCore.Components.Forms/lib/netstandard2.0
          packages/refdoc/Microsoft.Extensions.DependencyInjection.Abstractions/lib/netstandard2.0
          packages/refdoc/Microsoft.JSInterop/lib/netstandard2.0
          packages/refdoc/NETStandard.Library/build/netstandard2.0/ref
        --dllfiles
          packages/refdoc/Bolero/lib/netstandard2.1/Bolero.dll
          packages/refdoc/Bolero.Server/lib/netstandard2.1/Bolero.Server.dll

environment:
  GH_TOKEN:
    secure: dhFy1eZoqG4QPkKTuLFxix7QQMxaIyIpYjkvTU3CukYZz1CEOJeHfBSaT8tkPsGL

for:
- branches:
    only:
    - master
  on_success:
  - ps: .\tools\gh-pages.ps1 -env appveyor
