version: 0.11.{build}
image:
- Visual Studio 2019

build:
  verbosity: minimal

branches:
  except:
  - gh-pages

init:
- git config --global core.autocrlf input

install:
- git submodule update --init --recursive --remote
- ps: ./install.ps1

build_script:
- ps: dotnet build -c Release

environment:
  GH_TOKEN:
    secure: dhFy1eZoqG4QPkKTuLFxix7QQMxaIyIpYjkvTU3CukYZz1CEOJeHfBSaT8tkPsGL

for:
- branches:
    only:
    - master
  on_success:
  - ps: .\tools\gh-pages.ps1 -env appveyor
